---
description: client configuration, all timing is milli-second
sync:
  maxConnectionTotal: 100
  maxConnectionPerRoute: 10
  routes:
    api.google.com: 20
    api.facebook.com: 10
  timeout: 10000
  keepAlive: 15000
async:
  maxConnectionTotal: 100
  maxConnectionPerRoute: 10
  routes:
    api.google.com: 20
    api.facebook.com: 10
  reactor:
    ioThreadCount: 1
    connectTimeout: 10000
    soTimeout: 10000
  timeout: 10000
  keepAlive: 15000
tls:
  verifyHostname: false
  loadTrustStore: false
  trustStore: trust.keystore
  trustPass: password
  loadKeyStore: false
  keyStore: key.jks
  keyPass: password
oauth:
  tokenRenewBeforeExpired: 600000
  expiredRefreshRetryDelay: 5000
  earlyRefreshRetryDelay: 30000
  server_url: http://oauth2-token:6882
  authorization_code:
    uri: "/oauth2/token"
    client_id: d5a0fa30-408b-4068-884c-e1f36c9e20e7
    client_secret: DexYT2-OSHKQtNGsH0YYKQ
    redirect_uri: https://localhost:8080/authorization_code
    scope:
    - api_b.r
    - api_b.w
  client_credentials:
    uri: "/oauth2/token"
    client_id: d5a0fa30-408b-4068-884c-e1f36c9e20e7
    client_secret: DexYT2-OSHKQtNGsH0YYKQ
    scope:
    - api_b.r
    - api_b.w
