---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
- com.networknt.eventuate.common.impl.sync.AggregateCrud:
  - com.networknt.eventuate.client.EventuateLocalDBAggregateCrud
- com.networknt.eventuate.common.impl.AggregateEvents:
  - com.networknt.eventuate.client.KafkaAggregateSubscriptions
- com.networknt.eventuate.common.impl.AggregateCrud:
  - com.networknt.eventuate.common.impl.adapters.SyncToAsyncAggregateCrudAdapter
- com.networknt.eventuate.common.SnapshotManager:
  - com.networknt.eventuate.common.SnapshotManagerImpl
- com.networknt.eventuate.common.MissingApplyEventMethodStrategy:
  - com.networknt.eventuate.common.DefaultMissingApplyEventMethodStrategy
- com.networknt.eventuate.common.EventuateAggregateStore:
  - com.networknt.eventuate.common.impl.EventuateAggregateStoreImpl
- com.networknt.eventuate.queryservice.customer.CustomerViewRepository:
  - com.networknt.eventuate.queryservice.customer.CustomerViewRepositoryImpl
- com.networknt.eventuate.queryservice.customer.CustomerQueryService:
  - com.networknt.eventuate.queryservice.customer.CustomerQueryService
- com.networknt.eventuate.queryservice.customer.CustomerInfoUpdateService:
  - com.networknt.eventuate.queryservice.customer.CustomerInfoUpdateService
- com.networknt.eventuate.customer.view.CustomerQueryWorkflow:
  - com.networknt.eventuate.customer.view.CustomerQueryWorkflow
- com.networknt.eventuate.event.EventHandlerProcessor:
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningVoid
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningVoid
- com.networknt.eventuate.client.SubscriptionsRegistry:
  - com.networknt.eventuate.client.SubscriptionsRegistryImpl
- com.networknt.eventuate.account.command.account.Account:
  - com.networknt.eventuate.account.command.account.Account



# HandlerProvider implementation
- com.networknt.server.HandlerProvider:
  - com.networknt.eventuate.customer.view.PathHandlerProvider
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.eventuate.client.EventuateClientStartupHookProvider

- com.networknt.handler.MiddlewareHandler:
  - com.networknt.validator.ValidatorHandler
#Sanitizer Encode cross site scripting
  - com.networknt.sanitizer.SanitizerHandler
#SimpleAudit Log important info about the request into audit log
  - com.networknt.audit.AuditHandler
#Body Parse body based on content type in the header.
  - com.networknt.body.BodyHandler
#Security JWT token verification and scope verification (depending on SwaggerHandler)
  - com.networknt.security.JwtVerifyHandler
#Swagger Parsing swagger specification based on request uri and method.
  - com.networknt.swagger.SwaggerHandler
#Correlation Create correlationId if it doesn't exist in the request header and put it into the request header
  - com.networknt.correlation.CorrelationHandler
#Traceability Put traceabilityId into response header from request header if it exists
  - com.networknt.traceability.TraceabilityHandler
#Metrics In order to calculate response time accurately, this needs to be the second.
  - com.networknt.metrics.MetricsHandler
#Exception Global exception handler that needs to be called first.
  - com.networknt.exception.ExceptionHandler
