
# Singleton service factory configuration
singletons: 
 - javax.sql.DataSource: 
   - com.zaxxer.hikari.HikariDataSource: 
     jdbcUrl: "jdbc:mysql://localhost:3306/hello_world?useSSL=false"
     username: root
     password: "my-secret-pw"
     maximumPoolSize: 95
     useServerPrepStmts: true
     cachePrepStmts: true
     cacheCallableStmts: true
     prepStmtCacheSize: 4096
     prepStmtCacheSqlLimit: 2048
