#
# docker-compose-app.yml
#

version: '2'

#
# Services
#
services:


    #
    # Microservice: API A
    #
    apia:
        build: ~/networknt/light-java-example/ms_chain/api_a/security/
        ports:
            - "7001:7001"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_a/security:/config

    #
    # Microservice: API B
    #
    apib:
        build: ~/networknt/light-java-example/ms_chain/api_b/security/
        ports:
            - "7002:7002"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_b/security:/config

    #
    # Microservice: API C
    #
    apic:
        build: ~/networknt/light-java-example/ms_chain/api_c/security/
        ports:
            - "7003:7003"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_c/security:/config

    #
    # Microservice: API D
    #
    apid:
        build: ~/networknt/light-java-example/ms_chain/api_d/security/
        ports:
            - "7004:7004"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_d/security:/config

#
# Networks
#
networks:
    localnet:
        external: true