version: "3"

services:
  petstore:
    image: networknt/springboot-petstore
    network_mode: host
  proxy:
    image: networknt/light-proxy
    volumes:
    - ./config/http:/config
    network_mode: host
