version: '2'

services:
  apia:
    build: ./api_a/consuldocker
    ports:
    - "27441:27441"
    volumes:
    - ./api_a/consuldocker/config:/config
    networks:
    - localnet

  apib:
    build: ./api_b/consuldocker
    ports:
    - "27442:27442"
    volumes:
    - ./api_b/consuldocker/config:/config
    networks:
    - localnet

  apic:
    build: ./api_c/consuldocker
    ports:
    - "27443:27443"
    volumes:
    - ./api_c/consuldocker/config:/config
    networks:
    - localnet

  apid:
    build: ./api_d/consuldocker
    ports:
    - "27444:27444"
    volumes:
    - ./api_d/consuldocker/config:/config
    networks:
    - localnet


networks:
  localnet:
    # driver: bridge
    external: true