version: "2"
#
# Services
#
services:
   command-service:
      image: networknt/com.networknt.rest-command-1.0.0
      volumes:
        - ./docker/command-service/config:/config
      ports:
        - 8081:8081
      networks:
          - localnet

   query-service:
      image: networknt/com.networknt.rest-query-1.0.0
      volumes:
        - ./docker/query-service/config:/config
      ports:
        - 8082:8082
      networks:
          - localnet
# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true