#
# docker-compose-app.yml
#

version: '2'

#
# Services
#
services:


    #
    # Microservice: API A
    #
    apia:
        build: ~/networknt/light-java-example/ms_chain/api_a/apitoapi/
        ports:
            - "7001:7001"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_a/apionly:/config

    #
    # Microservice: API B
    #
    apib:
        build: ~/networknt/light-java-example/ms_chain/api_b/apitoapi/
        ports:
            - "7002:7002"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_b/apionly:/config

    #
    # Microservice: API C
    #
    apic:
        build: ~/networknt/light-java-example/ms_chain/api_c/apitoapi/
        ports:
            - "7003:7003"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_c/apionly:/config

    #
    # Microservice: API D
    #
    apid:
        build: ~/networknt/light-java-example/ms_chain/api_d/apitoapi/
        ports:
            - "7004:7004"
        networks:
            - localnet
        volumes:
            - ~/networknt/light-java-example/ms_chain/config/api_d/apionly:/config

#
# Networks
#
networks:
    localnet:
        external: true