description: client configuration, all timing is milli-second
sync:
  maxConnectionTotal: 100
  maxConnectionPerRoute: 10
  routes:
    api.google.com: 20
    api.facebook.com: 10
  timeout: 10000
  keepAlive: 15000
async:
  maxConnectionTotal: 100
  maxConnectionPerRoute: 10
  routes:
    api.google.com: 20
    api.facebook.com: 10
  reactor:
    ioThreadCount: 1
    connectTimeout: 10000
    soTimeout: 10000
  timeout: 10000
  keepAlive: 15000
tls:
  verifyHostname: false
  loadTrustStore: false
  trustStore: trust.keystore
  trustPass: password
  loadKeyStore: false
  keyStore: key.jks
  keyPass: password
oauth:
  tokenRenewBeforeExpired: 600000
  expiredRefreshRetryDelay: 5000
  earlyRefreshRetryDelay: 30000
  server_url: http://oauth2-token:6882
  authorization_code:
    uri: "/oauth2/token"
    client_id: 2970c16d-d39b-4ccc-96b0-d6dc4325340f
    client_secret: H4FpRXo_RLiNatcxce2d8g
    redirect_uri: https://localhost:8080/authorization_code
    scope:
    - api_c.r
    - api_c.w
  client_credentials:
    uri: "/oauth2/token"
    client_id: 2970c16d-d39b-4ccc-96b0-d6dc4325340f
    client_secret: H4FpRXo_RLiNatcxce2d8g
    scope:
    - api_c.r
    - api_c.w
